# -*- coding: utf-8 -*-
"""11. ARIMA time series forcasting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZG4GnNYR7ffgfTqmlmLsssGbu30GrPui
"""

# !pip install pmdarima
!pip install --upgrade pmdarima

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pmdarima

plt.style.use("dark_background")

df = pd.read_csv("AirPassengers.csv")
df.rename(columns={'#Passengers': 'Passengers'}, inplace=True)
print(df.dtypes)

df["Month"] = pd.to_datetime(df["Month"])

print(df.dtypes)

df.set_index("Month", inplace=True)

plt.plot(df["Passengers"])

from pmdarima.arima import ADFTest
adf_test = ADFTest(alpha = 0.05)
adt_test.should_diff(df)